WITH TARGET_TABLES AS (
    SELECT 'BANK' AS TBL_NAME FROM DUAL
    UNION ALL
    SELECT 'MESSAGE_FEED' FROM DUAL
    UNION ALL
    SELECT 'USER' FROM DUAL
    UNION ALL
    SELECT 'SHORT_CODE' FROM DUAL
)
SELECT
    T.TBL_NAME,
    A.ALERT_TYPE,
    A.ALERT_DATE,
    A.SEVERITY,
    TS.TABLESPACE_NAME,
FROM TARGET_TABLES T
LEFT JOIN ALERTS A
    ON T.TBL_NAME = A.OBJECT_NAME
LEFT JOIN USER_TABLESPACES TS
    ON TS.TABLESPACE_NAME = (
        SELECT TABLESPACE_NAME
        FROM USER_TABLES
        WHERE TABLE_NAME = T.TBL_NAME
    )
ORDER BY A.ALERT_DATE DESC;