apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  selector:
  matchLabels:
    app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
    spec:
      containers:
      - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m" # 0.25 of core
        limits:
          memory: "512Mi"
          cpu: "500m" # 0.5 of core
      ports:
      - containerPort: 80
      # --- Environment Variables from ConfigMap & Secret
      env:
        - name: UI_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: THEME_COLOR
        - name: DATABASE_PWD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
      # --- Mounting storage ---
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storage
    # --- Defining the volumes at pod level ---
    volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim