# Definitely didn't share the actual password LOL
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # This is the secret AKA password encoded in base64
  DB_PASSWORD: DB_PASSWORD
  # Not the actual password in my secret file LOL