apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: bank-app
  labels:
    app: queue
spec:
  clusterIP: None
  selector:
    app: queue
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: mgmt
    port: 15672
    targetPort: 15672