apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: bank-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bank-secret-store
    kind: ClusterSecretStore
  target:
    name: api-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: bank/api/db-password
  - secretKey: JWT_SECRET
    remoteRef:
      key: bank/api/jwt-secret
