apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audit-secrets
  namespace: bank-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bank-secret-store
    kind: ClusterSecretStore
  target:
    name: audit-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: bank/audit/db-password