apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: worker-secrets
  namespace: bank-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bank-secret-store
    kind: ClusterSecretStore
  target: 
    name: worker-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: bank/worker/db-password
  - secretKey: QUEUE_PASSWORD
    remoteRef:
      key: bank/worker/queue-password