apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: bank-app
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
      containers:
      - name: api
        image: gorathus6/financial-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres.bank-app.svc.cluster.local"
        - name: DB_USER
          value: api_user"
        - name: DB_PASSWORD
          valueFrom:
            securityKeyRef:
              name: api-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            name: api-secret
            key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
