apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone from 'manager' group to read secr>
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: Group
  name: empathmanager # case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io