apiVersion: v1
kind: Service
metadata:
  name: audit
  namespace: bank-app
  labels:
    app: audit
spec:
  type: ClusterIP
  selector:
    app: audit
  ports:
  - port: 80
    targetPort: 8082